# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_RRustTestPackage_wrappers", use_symbols = TRUE, package_name = "RRustTestPackage")

#' @docType package
#' @usage NULL
#' @useDynLib RRustTestPackage, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Testing if i can send http requests
#' @export
http_req <- function(url) .Call(wrap__http_req, url)


# nolint end
